### ISSUE TITLE
restructure layout to make the standard interface fit without scrollbars

### ISSUE THREAD

**Issue by ceriottm** [cosmo-epfl/chemiscope#10]
Idea would be to have two layouts depending on aspect ratio of the window, resized automaticallly to fit within it. also, the property listing for one frame should overlay the jsmol box, so that it always stay within the corresponding 1x1 block. if there are too many properties, there should be a small scrollbar within the overlay.  
mockup: 
![image](https://user-images.githubusercontent.com/1118823/73764027-97fcea80-4772-11ea-9a4f-21ce070fd12c.png)

**Comment by Luthaf** [comment]
Something to consider while we are at it is how a comparison mode (multiple structures visible at the same time) would look like.

**Comment by Luthaf** [comment]
Update: this is mostly done, moving the color bar below the plot is not currently possible (https://github.com/plotly/plotly.js/issues/1244).

I still need to change where the properties are displayed.

**Comment by Luthaf** [comment]
Done in 4fb05039324ca2deab9713e3ff0a93f8d289d46c
