### ISSUE TITLE
Allow to save the structure viewer output as PNG

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/chemiscope#115]
This should be easy, since all viewers are built on `canvas` elements, which can be rendered to an image with [`canvas.toDataURL`](https://developer.mozilla.org/fr/docs/Web/API/HTMLCanvasElement).

This should be nicer to use than using screenshots to extract structures views.

**Comment by ceriottm** [comment]
Something that would be *amazing* (and really make it very simple to go
from a chemiscope to a publication quality figure) would be to build an SVG
that combines the plotly canvas and the snapshots of the different panels.
as a separate laye (IDK if 3dmol.js can render with a transparent
background)

**Comment by Luthaf** [comment]
Having a "full chemiscope" svg output would be very interesting indeed! And it is something we could build on top of this feature.
