### ISSUE TITLE
Automatically change min/max bounds on axis when switching from linear to log scale

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/chemiscope#123]
Extracted from #109

-------

`@3dvkr` you're right on with making a threshold -- hypothetically if there's one value at 1E-12 and the rest between 1E-4 and 1E-2, we don't want the map to have the majority of the data squashed to one side and one lone point sitting on its own. Ideally it should be a tunable threshold, what do you think `@Luthaf` ?

_Originally posted by @rosecers in https://github.com/cosmo-epfl/chemiscope/issues/109#issuecomment-788922864_

**Comment by Luthaf** [comment]
There is already a min/max setting for the axis range, which should deal with this. Or are you referring to something different?

<img width="490" alt="Capture d’écran 2021-03-02 à 15 03 54" src="https://user-images.githubusercontent.com/6141587/109659956-90bc3200-7b68-11eb-9573-7c213f9368b0.png">

_Originally posted by @Luthaf in https://github.com/cosmo-epfl/chemiscope/issues/109#issuecomment-788931488_

**Comment by Luthaf** [comment]
No, I'm talking with respect to this. When going to log scale, the minimum should automatically change to some epsilon > 0. Agreed?

_Originally posted by @rosecers in https://github.com/cosmo-epfl/chemiscope/issues/109#issuecomment-788933414_

**Comment by Luthaf** [comment]
I think this is a separate issue from this one 😄. My feeling here is that we should not mess with these value automatically in case the user already set them to something meaningful. If the min is negative, we will get a warning once this improvement is implemented (actually, we don't have to check all values for the warning, only the min). If the min is positive but the data distribution is strange, I'd rather leave it to the user to adapt visualization as they want.

_Originally posted by @Luthaf in https://github.com/cosmo-epfl/chemiscope/issues/109#issuecomment-788935607_

**Comment by Luthaf** [comment]
Two notes:
1. we may also want to check the max (imagine the case where all values are
negative, what's the expected behavior?
2. if there are negative values we should de facto enforce as a minimum the
smallest positive value.

_Originally posted by @ceriottm in https://github.com/cosmo-epfl/chemiscope/issues/109#issuecomment-789025930_

**Comment by Luthaf** [comment]
> we may also want to check the max (imagine the case where all values are negative, what's the expected behavior?)

If everything is negative, nothing will be displayed. If the user want to display negative values in log scale, they can create a dataset with `- property` as a new property. 

The alternative I think you have in mind (correct me if I'm wrong) is to automatically take the negative; and then do a log scale. While convenient, I think this will be confusing (what should the ticks display?) and open the door to more transformations (`log(x + 1)`, `1/x`, etc.). I would love to have such data transformation available as a generic feature, but I don't think it is worth doing as a special case for displaying negative values in a log graph.

> if there are negative values we should de facto enforce as a minimum the smallest positive value.

This is already the case since negative values will map to NaN, which plotly will remove before adjusting the axes.

BTW, the code we use to get the min/max in the GUI values is broken, I'll open another issue =)

**Comment by 3dvkr** [comment]
> If the min is negative, we will get a warning once this improvement is implemented 

So the steps are for the time being to issue a warning if the min is negative and the scale mode is `log`? Would this also happen in `options.ts`? And after this warning is in place, we'd want to automatically change the min/max bounds?

**Comment by Luthaf** [comment]
> So the steps are for the time being to issue a warning if the min is negative and the scale mode is log? Would this also happen in options.ts?

Yes, that's the idea! These changes should not happen in options.ts but in map.ts, I'v written some instructions in https://github.com/cosmo-epfl/chemiscope/issues/109#issuecomment-788889334.

> And after this warning is in place, we'd want to automatically change the min/max bounds?

I'm not sure this is something we want to do in practice, this issue is here to discuss if it is worth it or not!

**Comment by Luthaf** [comment]
> When going to log scale, the minimum should automatically change to some epsilon > 0.

This is the only actionable thing I could pull out of this discussion, and is already implemented. Feel free to open a new issue if you need something else!
