### ISSUE TITLE
Make the property table easier to find

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/chemiscope#128]
This arose from a discussion with @NatalyLo. The property table is hard to find if you don't know it exists, and nothing indicate the users that they can click on "structure XXX" or "atom YYY" to open this table. 

We should make it easier to find, while not being too obnoxious. One suggestion is to add another button on the structure viewer (near duplicate/close/...) that would open this table (and maybe flash the existing buttons to signal the user they can use these as well). Alternatively, clicking on an already selected point on the map could open the table and flash existing buttons (clicking on non-selected point would select it).

----

The alternative would be to create some kind of tutorial for first time users, showing them parts of the page in an interactive way. I'm a bit reluctant to this since website tutorial can be very obnoxious when you already know what you are doing. This could be alleviated by storing a cookie to know if someone already looked at the tutorial. I don't know how this would play out  with different deployments of chemiscope, although only hosting the tutorial and cookie on chemiscope.org might be an OK solution.

**Comment by ceriottm** [comment]
Wouldn't a small [...] button, or hamburger icon, next to the structure
index be a good hint? there's no shortage of space close to the structure
number label
