### ISSUE TITLE
Adding a legend for atomic species in the structure viewer

### ISSUE THREAD

**Issue by jakublala** [cosmo-epfl/chemiscope#158]
Adding a legend might be a more neat and clear way to describe the different atomic species. As we are also allowing to download the structure screenshot, this would be very useful. Also, the current way of displaying atomic labels seems to be quite demanding for a larger structure.

**Comment by ceriottm** [comment]
TBH this seems overkill. labels are off by default, and colors follow
standard notation so I think we are good

**Comment by Luthaf** [comment]
I agree that adding a legend feels a bit overkill, but I'm also used to the standard set of colors and their meaning. 

> Also, the current way of displaying atomic labels seems to be quite demanding for a larger structure.

What do you mean by that? Adding labels takes more than 2-3s? Or something else?

**Comment by jakublala** [comment]
> What do you mean by that? Adding labels takes more than 2-3s? Or something else?

Yes, that's what I meant but I guess that's not such of an issue.
