### ISSUE TITLE
Add properties metadata

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/chemiscope#20]
Adding `description` and `units` for all properties in the dataset would be good

Places where we can display them:
- use `name (unit)` on the axis of the map (just `name` if unit is undefined or empty)
- show a tooltip with the `description` when selecting properties in the map setting? Not sure if this is possible
- show description in a tooltip in the "info" panel
- show unit in the "info" panel

Do you see other metadata we would want to attach to the properties?

**Comment by ceriottm** [comment]
These seem enough to me. I think a tooltip in the dropdown menu might be confusing. 
on the axis, let's use the SI-recommended name/units
