### ISSUE TITLE
Jupyter notebook widget does not show

### ISSUE THREAD

**Issue by koerper** [cosmo-epfl/chemiscope#209]
Hey,

I just tried to use the Jupyter widget of Chemiscope but unfortunately it doesn't show up in my Jupyter notebook.  I use Python 3.6 and Jupyter Notebook Version 6.0.3.

The commands I used are
```
import chemiscope

prpts = {
    "CV1": CV1,
    "CV2": CV2,
    "DP": some_data,
    "UE": more_data,
}

widget=chemiscope.show(frames=frames, properties=prpts)
widget
```
`frames` is a list of `ase` objects. 

When I run the cell, the jupyter doesn't complain but the browser console gives some errors (I attached them below). Is this any helpful? Please let me know if I can supply you with more information. If it helps you, I can also send you my data as a JSON file. I'd really like to get this running, the widget looks amazing.

Thanks in advance!

Cheers
Tim

* * *

```
Error: Could not create a view for model id 203ae927a6f941f380d2f8efc3c341d6
    v utils.js:119
    promise callback*T</t.prototype.create_view/t.state_change< manager-base.js:93
    promise callback*T</t.prototype.create_view manager-base.js:85
    display_model manager-base.js:72
    u extension.js:120
    promise callback*u/</< extension.js:119
    u extension.js:145
    append_mime_type outputarea.js:696
    append_display_data outputarea.js:659
    append_output outputarea.js:346
    handle_output outputarea.js:257
    output codecell.js:395
    _handle_output_message kernel.js:1197
    proxy jQuery
    _handle_iopub_message kernel.js:1224
    _finish_ws_message kernel.js:1016
    _msg_queue kernel.js:1007
    promise callback*Kernel.prototype._handle_ws_message kernel.js:1007
    proxy jQuery


Error: Could not create view
    v utils.js:119
    promise callback*T</t.prototype.display_model manager-base.js:72
    u extension.js:120
    promise callback*u/</< extension.js:119
    u extension.js:145
    append_mime_type outputarea.js:696
    append_display_data outputarea.js:659
    append_output outputarea.js:346
    handle_output outputarea.js:257
    output codecell.js:395
    _handle_output_message kernel.js:1197
    proxy jQuery
    _handle_iopub_message kernel.js:1224
    _finish_ws_message kernel.js:1016
    _msg_queue kernel.js:1007
    promise callback*Kernel.prototype._handle_ws_message kernel.js:1007
    proxy jQuery
utils.js:119

Uncaught (in promise) Error: Script error for "chemiscope-widget"
http://requirejs.org/docs/errors.html#scripterror
    makeError http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735

Uncaught (in promise) Error: Script error for "chemiscope-widget"
http://requirejs.org/docs/errors.html#scripterror
    makeError http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
```

**Comment by Luthaf** [comment]
Do you have files installed on your computer at `<python-prefix>/share/jupyter/nbextensions/chemiscope-widget/chemiscope-widget.min.js`? Where `<python-prefix>` is usually where your python libraries get installed, i.e. `<conda-prefix>` or `/home/xxx/.local/`, …

**Comment by koerper** [comment]
Yeah, the folder `~/.local/share/jupyter/nbextensions/chemiscope-widget` contains `chemiscope-widget.min.js`and `extension.js`

**Comment by koerper** [comment]
I had some earlier errors and spent some time fixing them. Although they are gone now, the error remains. There is a new error though:
```
The resource from “http://localhost:8888/static/chemiscope-widget.js?v=20211209175226” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

I'm using Firefox on Ubuntu 16.04

**Comment by ceriottm** [comment]
Wow! 16.04!? We still had Obama back then!

**Comment by koerper** [comment]
Hahaha, you got me there. I was kind of anxious to upgrade before finishing my thesis... this has been going for a while now. The voice in my head tells me 'never change a running system'.

Anyway, I tried using a conda environment with Python 3.6 which also didn't work. However, in a conda environment using Python 3.7 it worked. Apparently there are some conflicts in my ludicrous system setup for Python 3.6 which cause the problem. Sorry, I should've tried it in a conda environment before bothering you.

From my side the issue can be closed, thanks for the help. A really practical jupyter widget!
