### ISSUE TITLE
Refactor, cleanup and improvement linked to the pinning feature

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/chemiscope#45]
Taking the list from #25 review

- [x] Do not call `select({-1, -1}, guid)` to indicate removal, instead add specific functions for each possible action: `addPinned`, `removePinned`, `changeActivePinned`. Then `select` always act on the current `active` and only move the marker/change the structure
- [x] Remove the `starterGUID` parameter for `PropertyMap` constructor to allow using the map without a structure viewer. This should be easy to do after the above changes
- [ ] Extract code dealing with selected markers (things like `classList.toggle('chsp-active-structure-marker', false)`) to a separate `HTMLMarker` class doing all of this. 

On a related note, `src/map/map.ts` is getting quite large, so we should try to extract functionalities and potentially move it out of this file.

**Comment by ceriottm** [comment]
Re (3) I think that some of that could be done as part of the settings PR. All of those settings-related code could go in a separate file, would be tidier and easier to navigate.

**Comment by Luthaf** [comment]
- [ ] Use a `addPinned()` function instead of using setter. As far as I understand, a new pinned is currently automagically created when doing `map.active = guid` with a new guid.

**Comment by ceriottm** [comment]
Isn't this to be closed? Would be good to clean up a bit the open issues, many seem obsolete

**Comment by Luthaf** [comment]
There is still a remaining point from the initial comment.
