### ISSUE TITLE
Reverse size property in the map

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/chemiscope#52]
When something like energy is used as a property for dot size in the map, the most interesting points are the one with lowest energy, but they end up being the smallest.

We could provide an option to use `-<property>` instead of `<property>` for the size to support this use case.

**Comment by ceriottm** [comment]
I think we can use a "scale" option, that describes the relation between
the property and the radius. we could have "sqrt" (that should be default),
linear, log, -sqrt, etc.
Similarly, one should also be able to adjust the range.

**Comment by Luthaf** [comment]
> Similarly, one should also be able to adjust the range.

Do you means, setting min & max radius value?

**Comment by ceriottm** [comment]
I'm thinking to have size considered as an axis. So it's mapped between the
property range and sz_min -> sz_max, using a mapping function, very much
like an axis indeed.

**Comment by Luthaf** [comment]
Would that mean we also provide different mapping (sqrt, -x, …) for the x/y/z/color axis too?

**Comment by ceriottm** [comment]
If it's easy to achieve in plotly, I don't see why not. Wouldn't lose hours
otherwise
