### ISSUE TITLE
Symbols get messed up with multiple selections

### ISSUE THREAD

**Issue by ceriottm** [cosmo-epfl/chemiscope#56]
Using symbols to display categorical data interferes with selection highlighting, particularly when using multiple structure panels.

Expected behavior:
Highlighted structures are shown using the same symbol used for the category, which is just made a bit bigger and colored according to the structure panel color key. 

Observed behavior:
in 2D, a circle is used regardless of the underlying class
in 3D (even more problematic) the symbol of the active panel is used for all the selected structures (so that a structure with a square symbol might turn into a cross if I select a cross structure as the active one)

Might be linked to #50  and #11

**Comment by Luthaf** [comment]
The 2D behavior is expected, we have not implemented symbols with the 'HTML markers hack'. The 3D behavior looks like a bug =)

**Comment by ceriottm** [comment]
So mixed "bug/feature" issue it seems

**Comment by Luthaf** [comment]
Somehow related, if I click on an **already selected** point in 3D mode, the point is unselected and the viewer shows structure 1.
