### ISSUE TITLE
Default visualization settings in JSON input

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/chemiscope#6]
For the default interface, we could have a way to specify a visualization state in the input JSON file. 

On the map side, this means describing which property should be used as color/size/symbols, x/y/z ranges, etc.

On the structure viewer side, this means supercell settings, visualizations settings, etc.

---

This can be implemented by adding serialization/de-serialization of the settings to JSON, and having an additional section for these in the JSON input file.

**Comment by ceriottm** [comment]
Would like to resuscitate this. It'd be really good to have for the upcoming publication.

**Comment by Luthaf** [comment]
I am afraid implementing this right might require some refactoring of the overall architecture. Part of the issue is that right now, the main source of trust for all settings is the DOM itself (i.e. the "show the box" setting lives as a checkbox HTML element, which is queried as needed from JavaScript).

We could implement this in a brute force way, by having the `StructureViewer`, and `PropertiesMap` implement two functions, one dumping all parameters to a javascript object, and the other one loading the parameters and settings the corresponding values. The issues I can see with this are:
  1. duplication of a lot of code with existing settings handling (showing environments disable the packed cell option for example);
  2. the code would get harder to change and update: for each new settings we would have to remember to update the above functions; and change to existing settings would require to think carefully about backward compatibility to still be able to load previous version of the saved settings;

As far as doing it right goes, I think the best is to decouple the DOM and the settings themselves. I can think of two way of doing it right now: manually implement some kind of [Model-View-Controller](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) paradigm for the settings; or look into a [two-way data binding](https://stackoverflow.com/questions/13504906/what-is-two-way-binding) library that helps us to do exactly that.

**Comment by Luthaf** [comment]
After reading a few articles on two way data binding (https://blog.jeremylikness.com/blog/client-side-javascript-databinding-without-a-framework/, https://medium.com/better-programming/js-vanilla-two-way-binding-5a29bc86c787), this might not be too hard to implement.

Something like

```typescript
class Setting<T> {
    private value: T;
    private element: HTMLElement;
    constructor(value: T, id: string) {
        this.value = value;
        // get the HTML element and initialize the value
        return new Proxy(
            // add set function to also update the HTML value
        );
    }
}
```

The remaining issue I can see is how to distinguish between different HTML element (input vs select in particular), and how to deal with a request to set defaults as something that do not exists in the dataset (i.e. please plot `energy` vs `pressure`, but `pressure` does not exists)

**Comment by ceriottm** [comment]
I see. Yes, in i-PI I had implemented options in the first way you mention (each Object is mirrored by an InputObject that takes care of storing and loading its parameters) and I can agree that it is a pain for adding features, because you always need to touch two files and make sure that they stay in sync. 

Re consistency check, can't (and shouldn't) we raise errors in general if one asks to visualize a non-existent property? Currently seems we are relying that the interfaces that incorporate chemiscope widgets behave correctly, by having a minimum of error checking we can both get meaningful error messages and a fall-back option.
