### ISSUE TITLE
Add "download as standalone" button in default interface

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/chemiscope#7]
We already have the ability to generate a "standalone" visualization as an HTML file, the idea is to make it easier for users to download such file including their dataset.

- building the file automatically on Travis & deploying it to github pages
- when the user clicks on the button, download `standalone.html`, stringify the dataset back to JSON (including visualization state #6) and add it at the end of the file. 
- open a download dialog from Javascript for the user to save the file.

**Comment by ceriottm** [comment]
The PR #29 literally solves this issue, but not in spirit - we need first to be able to save the status of che viewer in a json (#24 etc) and then we can decide whether to download the json or a standalone viewer that incorporates it.

**Comment by Luthaf** [comment]
Done as part of #36
