### ISSUE TITLE
Some of the structure settings are dropped when switching structure

### ISSUE THREAD

**Issue by ceriottm** [cosmo-epfl/chemiscope#8]
Regardless of the choice of "trajectory" settings, some options such as packed cells, or the style for the environments, are reset when loading a new structure by clicking on the map or on the trajectory sliders.

**Comment by Luthaf** [comment]
> Uhm. I guess the question is related to #8: it is quite annoying that settings change when you click  another structure, so if it's easy (or feasible at all) to preserve *all* settings, also those that are not exposed in the viewer options, then I'd leave the menu as it adds features. If one would carefully tweak the representation and then lose it by accidentally clicking on the traj bar, it's better not to leave the temptation.

_Originally posted by @ceriottm in https://github.com/cosmo-epfl/chemiscope/issues/9#issuecomment-581495098_

**Comment by ceriottm** [comment]
This actually looks fixed to me. @Luthaf shall we close it?
