### ISSUE TITLE
Random errors when clicking randomly on the JSMol frame

### ISSUE THREAD

**Issue by ceriottm** [cosmo-epfl/chemiscope#9]
You may say that I'm getting what I deserve, but if you randomly click (click and drag while pressing left and right button in a random sequence seems to trigger this consistently) on the JSMol window, an error message appears 
![image](https://user-images.githubusercontent.com/1118823/73658876-6cf09900-4695-11ea-8717-8fbdc963807a.png)

**Comment by Luthaf** [comment]
>  random sequence seems to trigger this consistently

I like this description :smile:

**Comment by ceriottm** [comment]
Actually, seems this is triggered when opening JsMol context menu and overing with the mouse

**Comment by Luthaf** [comment]
I get a slightly different backtrace, but it also points to the JSmol contextual menu 

![image](https://user-images.githubusercontent.com/6141587/73660612-d45c1800-4698-11ea-8c32-bc6b7b0916ac.png)

**Comment by Luthaf** [comment]
Does not seems to happen with https://chemapps.stolaf.edu/jmol/jmol.htm, meaning there is some interaction with our code. I would guess JsMol replacing the global Error might be at play here: https://github.com/cosmo-epfl/chemiscope/blob/55757178946be0519f418b9791de8c0799902a3c/src/structure/widget.ts#L421-L429

**Comment by Luthaf** [comment]
https://github.com/cosmo-epfl/chemiscope/commit/d68db107fb3e03dc18cab061724d3a63f29a3938 should fix this. I think the issue comes from incompatibility between jquery and the bundled jquery-ui inside jsmol, cf https://sourceforge.net/p/jmol/mailman/message/33155014/ & https://stackoverflow.com/q/37914869/3041318

**Comment by Luthaf** [comment]
I could also disable the jsmol menu altogether, removing the need for jquery-ui

**Comment by ceriottm** [comment]
Uhm. I guess the question is related to #8: it is quite annoying that settings change when you click another structure, so if it's easy (or feasible at all) to preserve *all* settings, also those that are not exposed in the viewer options, then I'd leave the menu as it adds features. If one would carefully tweak the representation and then lose it by accidentally clicking on the traj bar, it's better not to leave the temptation.

**Comment by ceriottm** [comment]
I confirm that the current version does not trigger the error when clicking on the context menu.

**Comment by Luthaf** [comment]
Ok, great.
