### ISSUE TITLE
install, and easy import of write_chemiscope_input utils

### ISSUE THREAD

**Issue by ceriottm** [cosmo-epfl/chemiscope#94]
I find often myself using ugly code such as 

```
from os.path import expanduser
sys.path.append(expanduser('~')+'/lavoro/code/chemiscope/utils')
from chemiscope_input import write_chemiscope_input
```

to be able to write chemiscopes from my analysis notebooks.
I think it would be nice to have a pip package that installs the "utils" section of the chemiscope package, to facilitate its usage.
I was kind of torn as to whether these utils should rather live in a separate repo, but I actually think it makes sense for them to be associated with chemiscope, as that will simplify ensuring that the utils and the actual viewer stay in sync.

**Comment by Luthaf** [comment]
Yeah, that makes sense. I'll work on that if no-one beats me to it!
